import { euUI } from './ui';
import { MarketConfig } from '@/types/market.types';

export const euConfig: MarketConfig = {
  market: 'eu',
  name: 'European Union',
  locale: 'en-GB',
  pageSize: 'A4',
  direction: 'ltr',
  color: '#4f46e5',
  accentColor: '#3730a3',
  themes: [
    { id: 'eu-indigo', name: 'Europass Blue', primary: '#4f46e5', accent: '#3730a3', light: '#e0e7ff' },
    { id: 'eu-blue',   name: 'Cobalt',        primary: '#1d4ed8', accent: '#1e40af', light: '#dbeafe' },
    { id: 'eu-teal',   name: 'Teal',          primary: '#0d9488', accent: '#0f766e', light: '#ccfbf1' },
    { id: 'eu-green',  name: 'Forest',        primary: '#15803d', accent: '#166534', light: '#dcfce7' },
    { id: 'eu-slate',  name: 'Slate',         primary: '#475569', accent: '#334155', light: '#f1f5f9' },
    { id: 'eu-mono',   name: 'Monochrome',    primary: '#111827', accent: '#374151', light: '#f3f4f6' },
  ],
  fields: {
    photo: { visibility: 'optional', label: 'Profile Photo', helpText: 'Optional in most EU countries. Required for some (e.g., Germany, France).' },
    dateOfBirth: { visibility: 'optional', label: 'Date of Birth', helpText: 'Optional — some EU countries expect this on a CV.' },
    nationality: { visibility: 'optional', label: 'Nationality', helpText: 'Optional — required for cross-border applications.' },
    maritalStatus: { visibility: 'hidden' },
    idNumber: { visibility: 'hidden' },
    furigana: { visibility: 'hidden' },
    gender: { visibility: 'hidden' },
    nearestStation: { visibility: 'hidden' },
    commuteTime: { visibility: 'hidden' },
    emergencyContact: { visibility: 'hidden' },
    personalSeal: { visibility: 'hidden' },
  },
  sections: {
    objective: { enabled: true, required: false, order: 0, label: 'Personal Statement' },
    workExperience: { enabled: true, required: true, order: 1, label: 'Work Experience' },
    education: { enabled: true, required: true, order: 2, label: 'Education & Training' },
    skills: { enabled: true, required: false, order: 3, label: 'Digital & Technical Skills' },
    languages: { enabled: true, required: true, order: 4, label: 'Language Skills' },
    certifications: { enabled: true, required: false, order: 5, label: 'Courses & Certifications' },
    references: { enabled: true, required: false, order: 6, label: 'References' },
    selfPromotion: { enabled: false, required: false, order: 7 },
    reasonForApplication: { enabled: false, required: false, order: 8 },
  },
  pageLimitSuggestion: 2,
  languageLevelSystem: 'cefr',
  dateFormat: 'MMM yyyy',
  enableATSSuggestions: false,
  photoAspectRatio: 1,
  templates: [
    { id: 'eu-europass', name: 'Europass', description: 'Standard European Curriculum Vitae format' },
    { id: 'eu-modern',   name: 'Modern EU', description: 'Contemporary design with CEFR language grid' },
  ],
  ui: euUI,
};
