import { MarketConfig } from '@/types/market.types';

export const jpConfig: MarketConfig = {
  market: 'jp',
  name: '日本 (Japan)',
  locale: 'ja-JP',
  pageSize: 'A4',
  direction: 'ltr',
  color: '#dc2626',
  accentColor: '#b91c1c',
  themes: [
    { id: 'jp-red',    name: '赤 (Red)',    primary: '#dc2626', accent: '#b91c1c', light: '#fee2e2' },
    { id: 'jp-navy',   name: '紺 (Navy)',   primary: '#1e3a5f', accent: '#172b4a', light: '#dbeafe' },
    { id: 'jp-black',  name: '黒 (Black)',  primary: '#111827', accent: '#374151', light: '#f3f4f6' },
    { id: 'jp-green',  name: '緑 (Green)',  primary: '#15803d', accent: '#166534', light: '#dcfce7' },
    { id: 'jp-purple', name: '紫 (Purple)', primary: '#7c3aed', accent: '#6d28d9', light: '#ede9fe' },
  ],
  fields: {
    photo: { visibility: 'required', label: '写真', helpText: '3×4cm の証明写真を貼付してください。' },
    dateOfBirth: { visibility: 'required', label: '生年月日', helpText: '元号（和暦）または西暦で記入してください。' },
    nationality: { visibility: 'optional', label: '国籍', helpText: '外国籍の場合は記入してください。' },
    maritalStatus: { visibility: 'hidden' },
    idNumber: { visibility: 'hidden' },
    furigana: { visibility: 'required', label: 'ふりがな', helpText: '氏名のふりがなを平仮名で記入してください。' },
    gender: { visibility: 'required', label: '性別', helpText: '履歴書の公式フォーマットに準じます。' },
    nearestStation: { visibility: 'required', label: '最寄り駅', helpText: '自宅最寄りの駅名と路線名を記入してください。' },
    commuteTime: { visibility: 'required', label: '通勤時間（分）', helpText: '自宅から勤務先までの通勤時間の目安。' },
    emergencyContact: { visibility: 'optional', label: '緊急連絡先' },
    personalSeal: { visibility: 'required', label: '捺印', helpText: '一部の企業では捺印（認印）が求められます。' },
  },
  sections: {
    objective: { enabled: false, required: false, order: 0, label: '志望動機' },
    workExperience: { enabled: true, required: true, order: 1, label: '職歴' },
    education: { enabled: true, required: true, order: 2, label: '学歴' },
    skills: { enabled: true, required: false, order: 3, label: '免許・資格' },
    languages: { enabled: true, required: false, order: 4, label: '語学スキル' },
    certifications: { enabled: true, required: false, order: 5, label: '免許・資格' },
    references: { enabled: false, required: false, order: 6 },
    selfPromotion: { enabled: true, required: true, order: 7, label: '自己PR' },
    reasonForApplication: { enabled: true, required: true, order: 8, label: '志望動機' },
  },
  languageLevelSystem: 'jlpt',
  dateFormat: 'yyyy年M月',
  enableATSSuggestions: false,
  photoAspectRatio: 0.75,
  templates: [
    { id: 'jp-rirekisho', name: '履歴書', description: '日本の公式履歴書フォーマット（JIS規格準拠）' },
    { id: 'jp-shokumu',   name: '職務経歴書', description: '職務経歴書形式（キャリア採用向け）' },
  ],
};
