import { MarketConfig } from '@/types/market.types';

export const latamConfig: MarketConfig = {
  market: 'latam',
  name: 'Latin America',
  locale: 'es-419',
  pageSize: 'Letter',
  direction: 'ltr',
  color: '#ea580c',
  accentColor: '#c2410c',
  themes: [
    { id: 'latam-orange', name: 'Naranja',    primary: '#ea580c', accent: '#c2410c', light: '#ffedd5' },
    { id: 'latam-red',    name: 'Rojo',       primary: '#dc2626', accent: '#b91c1c', light: '#fee2e2' },
    { id: 'latam-green',  name: 'Verde',      primary: '#15803d', accent: '#166534', light: '#dcfce7' },
    { id: 'latam-blue',   name: 'Azul',       primary: '#2563eb', accent: '#1d4ed8', light: '#dbeafe' },
    { id: 'latam-violet', name: 'Violeta',    primary: '#7c3aed', accent: '#6d28d9', light: '#ede9fe' },
    { id: 'latam-mono',   name: 'Monocromático', primary: '#111827', accent: '#374151', light: '#f3f4f6' },
  ],
  fields: {
    photo: { visibility: 'required', label: 'Foto de Perfil', helpText: 'Una foto profesional es esperada en la mayoría de los países latinoamericanos.' },
    dateOfBirth: { visibility: 'required', label: 'Fecha de Nacimiento', helpText: 'Requerido en la mayoría de los CVs latinoamericanos.' },
    nationality: { visibility: 'required', label: 'Nacionalidad' },
    maritalStatus: { visibility: 'required', label: 'Estado Civil' },
    idNumber: { visibility: 'optional', label: 'RUT / DNI / CURP / Cédula', helpText: 'Número de identificación nacional (opcional según el país).' },
    furigana: { visibility: 'hidden' },
    gender: { visibility: 'optional', label: 'Género' },
    nearestStation: { visibility: 'hidden' },
    commuteTime: { visibility: 'hidden' },
    emergencyContact: { visibility: 'hidden' },
    personalSeal: { visibility: 'hidden' },
  },
  sections: {
    objective: { enabled: true, required: true, order: 0, label: 'Objetivo Profesional' },
    workExperience: { enabled: true, required: true, order: 1, label: 'Experiencia Laboral' },
    education: { enabled: true, required: true, order: 2, label: 'Formación Académica' },
    skills: { enabled: true, required: false, order: 3, label: 'Habilidades' },
    languages: { enabled: true, required: false, order: 4, label: 'Idiomas' },
    certifications: { enabled: true, required: false, order: 5, label: 'Certificaciones y Cursos' },
    references: { enabled: true, required: true, order: 6, label: 'Referencias' },
    selfPromotion: { enabled: false, required: false, order: 7 },
    reasonForApplication: { enabled: false, required: false, order: 8 },
  },
  pageLimitSuggestion: 2,
  languageLevelSystem: 'generic',
  dateFormat: 'MMM yyyy',
  enableATSSuggestions: false,
  photoAspectRatio: 0.75,
  templates: [
    { id: 'latam-traditional', name: 'Tradicional', description: 'Formato clásico latinoamericano con foto y datos personales' },
    { id: 'latam-modern',      name: 'Moderno',      description: 'Diseño contemporáneo con sidebar de color' },
  ],
};
