import { MarketUI } from '@/types/market.types';

export const enUI: MarketUI = {
  back: 'Back', next: 'Next', save: 'Save', saving: 'Saving…', saved: 'Saved',
  clear: 'Clear', clearConfirmTitle: 'Clear all data?',
  clearConfirmBody: 'This will erase everything on this CV. This action cannot be undone.',
  import: 'Import', exportPDF: 'Export PDF', generating: 'Generating…',
  done: 'Done!', failed: 'Failed', cancel: 'Cancel', add: 'Add', apply: 'Apply',
  markets: '← Markets', privacyOn: 'Private', privacyOff: 'Privacy',

  personalInfoTitle: 'Personal Information',
  personalInfoDesc: 'Your contact details and basic information.',
  firstName: 'First Name', firstNamePlaceholder: 'John',
  lastName: 'Last Name', lastNamePlaceholder: 'Smith',
  email: 'Email', emailPlaceholder: 'john@example.com',
  phone: 'Phone', phonePlaceholder: '+1 555 000 0000',
  city: 'City', cityPlaceholder: 'New York',
  country: 'Country', countryPlaceholder: 'United States',
  linkedIn: 'LinkedIn URL', website: 'Website / Portfolio',

  maritalSelect: 'Select…', maritalSingle: 'Single',
  maritalMarried: 'Married', maritalDivorced: 'Divorced',
  maritalWidowed: 'Widowed', maritalPreferNot: 'Prefer not to say',

  genderSelect: 'Select…', genderMale: 'Male', genderFemale: 'Female',
  genderOther: 'Other', genderPreferNot: 'Prefer not to say',

  objectiveDesc: 'A brief summary of your professional background and career goals.',
  objectivePlaceholder: 'Results-driven software engineer with 5+ years of experience building scalable web applications. Proven track record of delivering high-impact features that improve user engagement by 30%+.',
  objectiveAimHint: ' (aim for 2–4 sentences)',
  skillsDesc: 'Add your technical and professional skills.',
  languagesDesc: 'Describe your language proficiency.',
  certsDesc: 'List your professional certifications and licences.',
  refsDesc: 'Professional references who can vouch for your work.',

  workJobTitle: 'Job Title', workJobTitlePlaceholder: 'Software Engineer',
  workCompany: 'Company', workCompanyPlaceholder: 'Acme Corp',
  workLocation: 'Location', workLocationPlaceholder: 'New York, NY',
  workEmploymentType: 'Employment Type',
  workDescription: 'Description', workDescPlaceholder: '• Led development of…',
  addWork: 'Add Work Experience', newPosition: 'New Position', newCompany: 'Company name',
  employmentTypes: { fullTime: 'Full-time', partTime: 'Part-time', contract: 'Contract', freelance: 'Freelance', internship: 'Internship' },

  addEducation: 'Add Education', newDegree: 'New Degree', newInstitution: 'Institution',
  degree: 'Degree', degreePlaceholder: 'Bachelor of Science',
  fieldOfStudy: 'Field of Study', fieldOfStudyPlaceholder: 'Computer Science',
  institution: 'Institution', institutionPlaceholder: 'University of California',
  location: 'Location', locationPlaceholder: 'Berkeley, CA',
  gpa: 'GPA (optional)', honors: 'Honors / Awards',

  addSkill: 'Add', skillPlaceholder: 'e.g. Python, Project Management',
  skillCategory: 'Category (optional)', skillCategoryPlaceholder: 'General',
  noSkillsYet: 'No skills added yet. Type a skill above and press Enter.',
  skillLevels: ['Beginner', 'Basic', 'Intermediate', 'Advanced', 'Expert'],

  addLanguage: 'Add', languagePlaceholder: 'e.g. Spanish, French',
  noLanguagesYet: 'No languages added yet.',
  nativeLabel: 'Native', langCertLabel: 'Certification / Score', langCertPlaceholder: 'e.g. IELTS 7.5',

  addCertification: 'Add Certification', newCertification: 'New Certification',
  certName: 'Certification Name', certNamePlaceholder: 'AWS Solutions Architect',
  certIssuer: 'Issuing Organization', certIssuerPlaceholder: 'Amazon Web Services',
  certDate: 'Date Issued', certExpiry: 'Expiry Date',
  certCredential: 'Credential ID / URL', certCredentialPlaceholder: 'ABC123 or https://…',

  addReference: 'Add Reference', newReference: 'New Reference', newReferenceSubtitle: 'Title, Company',
  refName: 'Full Name', refNamePlaceholder: 'Jane Doe',
  refJobTitle: 'Job Title', refJobTitlePlaceholder: 'Senior Manager',
  refCompany: 'Company', refCompanyPlaceholder: 'Acme Corp',
  refRelationship: 'Relationship', refRelationshipPlaceholder: 'Direct manager',

  templateTitle: 'Choose a Template',
  templateDesc: 'Select the layout and color theme that best fits your target role.',
  colorTheme: 'Color Theme', selectedLabel: 'Selected:',

  importTitle: 'Import from Existing CV',
  importDesc: 'Paste your existing CV as plain text or Markdown. We\'ll extract your information and fill in the form automatically.',
  importWarning: 'Parsing is heuristic — review and correct the extracted data before exporting. Photos are not imported.',
  importPlaceholder: 'Paste your CV text or Markdown here…',
  parseCV: 'Parse CV', applyToBuilder: 'Apply to Builder', editText: '← Edit text',
  importSuccess: 'Imported successfully!',
  importSuccessDesc: 'Review and complete the missing fields in the builder.',
  previewLabels: {
    name: 'Name', email: 'Email', phone: 'Phone', linkedin: 'LinkedIn',
    summary: 'Summary', workExperience: 'Work Experience', entries: 'entries extracted',
    education: 'Education', skills: 'Skills', languages: 'Languages', certifications: 'Certifications',
    workPreview: 'Work Experience Preview', noTitle: '(no title)', notFound: 'not found', moreSuffix: 'more…',
  },

  characters: 'characters',
  noItemsYet: 'No items added yet.',
};

export const euUI: MarketUI = {
  ...enUI,
  phonePlaceholder: '+32 470 00 00 00',
  city: 'City', cityPlaceholder: 'Brussels',
  country: 'Country', countryPlaceholder: 'Belgium',
  firstNamePlaceholder: 'Sofia',
  lastNamePlaceholder: 'Müller',
  emailPlaceholder: 'sofia@example.eu',
  workLocationPlaceholder: 'Berlin, Germany',
  institutionPlaceholder: 'University of Amsterdam',
  locationPlaceholder: 'Amsterdam, Netherlands',
  objectiveDesc: 'Write a concise personal statement for European employers, highlighting international experience, languages, and role fit.',
  objectivePlaceholder: 'Project coordinator with 5+ years of experience delivering cross-border digital initiatives across European teams. Skilled in stakeholder communication, process improvement, and multilingual collaboration, with a track record of improving delivery predictability and documentation quality.',
  objectiveAimHint: ' (aim for 3–5 lines)',
  skillPlaceholder: 'e.g. Stakeholder coordination, GDPR, Data analysis',
  skillCategoryPlaceholder: 'e.g. Digital skills',
  languagePlaceholder: 'e.g. German, French, Spanish',
  langCertPlaceholder: 'e.g. CEFR C1, DELF B2',
  certIssuerPlaceholder: 'European Commission / Coursera / PMI',
  certNamePlaceholder: 'PRINCE2 Foundation / EU Project Management',
  workCompanyPlaceholder: 'European Digital Agency',
  workJobTitlePlaceholder: 'Project Coordinator',
  workDescPlaceholder: '• Coordinated a cross-border rollout across teams in Germany, Spain, and the Netherlands, improving reporting consistency and delivery visibility.',
  degreePlaceholder: 'Master of Science',
  fieldOfStudyPlaceholder: 'International Business',
  refNamePlaceholder: 'Elena Rossi',
  refJobTitlePlaceholder: 'Programme Manager',
  refCompanyPlaceholder: 'European Digital Agency',
  refRelationshipPlaceholder: 'Project sponsor',
};

export const esUI: MarketUI = {
  back: 'Atrás', next: 'Siguiente', save: 'Guardar', saving: 'Guardando…', saved: 'Guardado',
  clear: 'Limpiar', clearConfirmTitle: '¿Limpiar todos los datos?',
  clearConfirmBody: 'Esto borrará todo en este CV. Esta acción no se puede deshacer.',
  import: 'Importar', exportPDF: 'Exportar PDF', generating: 'Generando…',
  done: '¡Listo!', failed: 'Error', cancel: 'Cancelar', add: 'Añadir', apply: 'Aplicar',
  markets: '← Mercados', privacyOn: 'Privado', privacyOff: 'Privacidad',

  personalInfoTitle: 'Información Personal',
  personalInfoDesc: 'Tus datos de contacto e información básica.',
  firstName: 'Nombre', firstNamePlaceholder: 'Juan',
  lastName: 'Apellido', lastNamePlaceholder: 'García',
  email: 'Correo Electrónico', emailPlaceholder: 'juan@ejemplo.com',
  phone: 'Teléfono', phonePlaceholder: '+54 555 000 0000',
  city: 'Ciudad', cityPlaceholder: 'Buenos Aires',
  country: 'País', countryPlaceholder: 'Argentina',
  linkedIn: 'URL de LinkedIn', website: 'Sitio Web / Portafolio',

  maritalSelect: 'Seleccionar', maritalSingle: 'Soltero/a',
  maritalMarried: 'Casado/a', maritalDivorced: 'Divorciado/a',
  maritalWidowed: 'Viudo/a', maritalPreferNot: 'Prefiero no decir',

  genderSelect: 'Seleccionar', genderMale: 'Masculino', genderFemale: 'Femenino',
  genderOther: 'Otro', genderPreferNot: 'Prefiero no decir',

  objectiveDesc: 'Describe tu perfil profesional y objetivos de carrera.',
  objectivePlaceholder: 'Profesional con más de 5 años de experiencia en desarrollo de software, orientado a resultados y comprometido con la excelencia técnica. Busco aportar mi experiencia en un equipo dinámico y de alto rendimiento.',
  objectiveAimHint: '',
  skillsDesc: 'Añade tus habilidades técnicas y profesionales.',
  languagesDesc: 'Describe tu nivel de dominio de cada idioma.',
  certsDesc: 'Lista tus certificaciones y cursos profesionales.',
  refsDesc: 'Incluye 2–3 referencias profesionales con sus datos de contacto.',

  workJobTitle: 'Cargo', workJobTitlePlaceholder: 'Ingeniero de Software',
  workCompany: 'Empresa', workCompanyPlaceholder: 'Empresa S.A.',
  workLocation: 'Ubicación', workLocationPlaceholder: 'Buenos Aires, Argentina',
  workEmploymentType: 'Tipo de Empleo',
  workDescription: 'Descripción', workDescPlaceholder: '• Lideré el desarrollo de…',
  addWork: 'Añadir Experiencia Laboral', newPosition: 'Nuevo Puesto', newCompany: 'Nombre de la empresa',
  employmentTypes: { fullTime: 'Tiempo Completo', partTime: 'Tiempo Parcial', contract: 'Contrato', freelance: 'Freelance', internship: 'Pasantía' },

  addEducation: 'Añadir Educación', newDegree: 'Nuevo Título', newInstitution: 'Institución',
  degree: 'Título', degreePlaceholder: 'Licenciatura en Ciencias',
  fieldOfStudy: 'Área de Estudio', fieldOfStudyPlaceholder: 'Informática',
  institution: 'Institución', institutionPlaceholder: 'Universidad de Buenos Aires',
  location: 'Ubicación', locationPlaceholder: 'Buenos Aires, Argentina',
  gpa: 'Promedio (opcional)', honors: 'Honores / Premios',

  addSkill: 'Añadir', skillPlaceholder: 'p. ej. Python, Gestión de Proyectos',
  skillCategory: 'Categoría (opcional)', skillCategoryPlaceholder: 'General',
  noSkillsYet: 'Aún no hay habilidades. Escribe una arriba y presiona Enter.',
  skillLevels: ['Principiante', 'Básico', 'Intermedio', 'Avanzado', 'Experto'],

  addLanguage: 'Añadir', languagePlaceholder: 'p. ej. Inglés, Francés',
  noLanguagesYet: 'Aún no hay idiomas añadidos.',
  nativeLabel: 'Nativo/a', langCertLabel: 'Certificación / Puntaje', langCertPlaceholder: 'p. ej. IELTS 7.5',

  addCertification: 'Añadir Certificación', newCertification: 'Nueva Certificación',
  certName: 'Nombre de la Certificación', certNamePlaceholder: 'AWS Solutions Architect',
  certIssuer: 'Organización Emisora', certIssuerPlaceholder: 'Amazon Web Services',
  certDate: 'Fecha de Emisión', certExpiry: 'Fecha de Vencimiento',
  certCredential: 'ID de Credencial / URL', certCredentialPlaceholder: 'ABC123 o https://…',

  addReference: 'Añadir Referencia', newReference: 'Nueva Referencia', newReferenceSubtitle: 'Cargo, Empresa',
  refName: 'Nombre Completo', refNamePlaceholder: 'María García',
  refJobTitle: 'Cargo', refJobTitlePlaceholder: 'Gerente Senior',
  refCompany: 'Empresa', refCompanyPlaceholder: 'Empresa S.A.',
  refRelationship: 'Relación', refRelationshipPlaceholder: 'Jefe directo',

  templateTitle: 'Elegir Plantilla',
  templateDesc: 'Selecciona el diseño y tema de color que mejor se adapte a tu perfil.',
  colorTheme: 'Tema de Color', selectedLabel: 'Seleccionado:',

  importTitle: 'Importar CV Existente',
  importDesc: 'Pega tu CV como texto sin formato o Markdown. Extraeremos tu información y rellenaremos el formulario automáticamente.',
  importWarning: 'El análisis es heurístico — revisa y corrige los datos extraídos antes de exportar. Las fotos no se importan.',
  importPlaceholder: 'Pega tu CV o Markdown aquí…',
  parseCV: 'Analizar CV', applyToBuilder: 'Aplicar al Constructor', editText: '← Editar texto',
  importSuccess: '¡Importado con éxito!',
  importSuccessDesc: 'Revisa y completa los campos faltantes en el constructor.',
  previewLabels: {
    name: 'Nombre', email: 'Correo', phone: 'Teléfono', linkedin: 'LinkedIn',
    summary: 'Resumen', workExperience: 'Experiencia Laboral', entries: 'entradas extraídas',
    education: 'Educación', skills: 'Habilidades', languages: 'Idiomas', certifications: 'Certificaciones',
    workPreview: 'Vista Previa de Experiencia', noTitle: '(sin título)', notFound: 'no encontrado', moreSuffix: 'más…',
  },

  characters: 'caracteres',
  noItemsYet: 'Aún no hay elementos añadidos.',
};

// GB — British English (same keys as enUI, British placeholders & conventions)
export const gbUI: MarketUI = {
  ...enUI,
  phonePlaceholder: '+44 7700 900000',
  city: 'Town / City', cityPlaceholder: 'London',
  country: 'Country', countryPlaceholder: 'United Kingdom',
  workLocationPlaceholder: 'London, UK',
  institutionPlaceholder: 'University of Oxford',
  locationPlaceholder: 'Oxford, UK',
  templateTitle: 'Choose a Template',
  templateDesc: 'Select the layout and colour theme that best fits your target role.',
  firstNamePlaceholder: 'James',
  lastNamePlaceholder: 'Williams',
  emailPlaceholder: 'james@example.co.uk',
  objectiveDesc: 'Write a concise personal profile (3–5 lines) highlighting your skills and career aims.',
  objectivePlaceholder: 'Motivated software engineer with 5+ years of experience delivering scalable web applications. Adept at collaborating with cross-functional teams to build high-quality products. Seeking a senior role where I can drive technical excellence and contribute to product growth.',
  objectiveAimHint: ' (aim for 3–5 lines)',
  certsDesc: 'List your professional qualifications and certifications.',
  refsDesc: 'Two professional referees are expected — or write "References available on request".',
};

// AU — Australian English
export const auUI: MarketUI = {
  ...enUI,
  phonePlaceholder: '+61 4 0000 0000',
  city: 'Suburb / City', cityPlaceholder: 'Sydney',
  country: 'Country', countryPlaceholder: 'Australia',
  workLocationPlaceholder: 'Sydney, NSW',
  institutionPlaceholder: 'University of Melbourne',
  locationPlaceholder: 'Melbourne, VIC',
  firstNamePlaceholder: 'Liam',
  lastNamePlaceholder: 'Johnson',
  emailPlaceholder: 'liam@example.com.au',
  objectiveDesc: 'Summarise your career background and what you bring to the role (2–4 sentences).',
  objectivePlaceholder: 'Passionate software developer with 5+ years of experience in full-stack development. Skilled in delivering robust solutions in fast-paced environments. Looking to bring my expertise to a collaborative and innovative team.',
  objectiveAimHint: ' (aim for 2–4 sentences)',
  refsDesc: 'Include 2 professional referees with contact details. Academic referees are acceptable for recent graduates.',
};

// IN — Indian English
export const inUI: MarketUI = {
  ...enUI,
  phonePlaceholder: '+91 98765 43210',
  city: 'City', cityPlaceholder: 'Mumbai',
  country: 'Country', countryPlaceholder: 'India',
  workLocationPlaceholder: 'Mumbai, Maharashtra',
  institutionPlaceholder: 'Indian Institute of Technology',
  locationPlaceholder: 'Mumbai, Maharashtra',
  firstNamePlaceholder: 'Rahul',
  lastNamePlaceholder: 'Sharma',
  emailPlaceholder: 'rahul@example.com',
  workJobTitlePlaceholder: 'Software Engineer',
  workCompanyPlaceholder: 'Infosys / TCS / Wipro',
  objectiveDesc: 'State your career objective and the value you aim to bring to the organisation.',
  objectivePlaceholder: 'Highly motivated software engineer with 5+ years of experience in software development and system design. Seeking a challenging role in a reputed organisation where I can apply my technical skills and contribute to the company\'s growth.',
  objectiveAimHint: ' (aim for 3–5 lines)',
  refsDesc: 'Include 2–3 professional references with contact details.',
};

// PT-BR — Brazilian Portuguese
export const ptBrUI: MarketUI = {
  back: 'Voltar', next: 'Próximo', save: 'Salvar', saving: 'Salvando…', saved: 'Salvo',
  clear: 'Limpar', clearConfirmTitle: 'Limpar todos os dados?',
  clearConfirmBody: 'Isso apagará todo o conteúdo deste currículo. Esta ação não pode ser desfeita.',
  import: 'Importar', exportPDF: 'Exportar PDF', generating: 'Gerando…',
  done: 'Pronto!', failed: 'Erro', cancel: 'Cancelar', add: 'Adicionar', apply: 'Aplicar',
  markets: '← Mercados', privacyOn: 'Privado', privacyOff: 'Privacidade',

  personalInfoTitle: 'Informações Pessoais',
  personalInfoDesc: 'Seus dados de contato e informações básicas.',
  firstName: 'Nome', firstNamePlaceholder: 'João',
  lastName: 'Sobrenome', lastNamePlaceholder: 'Silva',
  email: 'E-mail', emailPlaceholder: 'joao@exemplo.com',
  phone: 'Telefone', phonePlaceholder: '+55 11 90000-0000',
  city: 'Cidade', cityPlaceholder: 'São Paulo',
  country: 'País', countryPlaceholder: 'Brasil',
  linkedIn: 'URL do LinkedIn', website: 'Site / Portfólio',

  maritalSelect: 'Selecionar', maritalSingle: 'Solteiro/a',
  maritalMarried: 'Casado/a', maritalDivorced: 'Divorciado/a',
  maritalWidowed: 'Viúvo/a', maritalPreferNot: 'Prefiro não informar',

  genderSelect: 'Selecionar', genderMale: 'Masculino', genderFemale: 'Feminino',
  genderOther: 'Outro', genderPreferNot: 'Prefiro não informar',

  objectiveDesc: 'Descreva seu perfil profissional e objetivos de carreira.',
  objectivePlaceholder: 'Profissional com mais de 5 anos de experiência em desenvolvimento de software, orientado a resultados e comprometido com a excelência técnica. Busco contribuir com minha experiência em uma equipe dinâmica.',
  objectiveAimHint: '',
  skillsDesc: 'Adicione suas habilidades técnicas e profissionais.',
  languagesDesc: 'Descreva sua proficiência nos idiomas que você fala.',
  certsDesc: 'Liste suas certificações e cursos profissionais.',
  refsDesc: 'Inclua 2–3 referências profissionais com dados de contato.',

  workJobTitle: 'Cargo', workJobTitlePlaceholder: 'Engenheiro de Software',
  workCompany: 'Empresa', workCompanyPlaceholder: 'Empresa Ltda.',
  workLocation: 'Localização', workLocationPlaceholder: 'São Paulo, SP',
  workEmploymentType: 'Tipo de Vínculo',
  workDescription: 'Descrição', workDescPlaceholder: '• Liderei o desenvolvimento de…',
  addWork: 'Adicionar Experiência Profissional', newPosition: 'Novo Cargo', newCompany: 'Nome da empresa',
  employmentTypes: { fullTime: 'CLT / Integral', partTime: 'Meio Período', contract: 'PJ / Contrato', freelance: 'Freelance', internship: 'Estágio' },

  addEducation: 'Adicionar Formação', newDegree: 'Nova Formação', newInstitution: 'Instituição',
  degree: 'Grau', degreePlaceholder: 'Bacharelado em Ciências',
  fieldOfStudy: 'Área de Formação', fieldOfStudyPlaceholder: 'Ciência da Computação',
  institution: 'Instituição', institutionPlaceholder: 'Universidade de São Paulo',
  location: 'Localização', locationPlaceholder: 'São Paulo, SP',
  gpa: 'CRA / CR (opcional)', honors: 'Honras / Prêmios',

  addSkill: 'Adicionar', skillPlaceholder: 'ex: Python, Gestão de Projetos',
  skillCategory: 'Categoria (opcional)', skillCategoryPlaceholder: 'Geral',
  noSkillsYet: 'Nenhuma habilidade adicionada. Digite acima e pressione Enter.',
  skillLevels: ['Iniciante', 'Básico', 'Intermediário', 'Avançado', 'Especialista'],

  addLanguage: 'Adicionar', languagePlaceholder: 'ex: Inglês, Espanhol',
  noLanguagesYet: 'Nenhum idioma adicionado ainda.',
  nativeLabel: 'Nativo/a', langCertLabel: 'Certificação / Pontuação', langCertPlaceholder: 'ex: TOEFL 100',

  addCertification: 'Adicionar Certificação', newCertification: 'Nova Certificação',
  certName: 'Nome da Certificação', certNamePlaceholder: 'AWS Solutions Architect',
  certIssuer: 'Organização Emissora', certIssuerPlaceholder: 'Amazon Web Services',
  certDate: 'Data de Emissão', certExpiry: 'Data de Validade',
  certCredential: 'ID da Credencial / URL', certCredentialPlaceholder: 'ABC123 ou https://…',

  addReference: 'Adicionar Referência', newReference: 'Nova Referência', newReferenceSubtitle: 'Cargo, Empresa',
  refName: 'Nome Completo', refNamePlaceholder: 'Maria Silva',
  refJobTitle: 'Cargo', refJobTitlePlaceholder: 'Gerente Sênior',
  refCompany: 'Empresa', refCompanyPlaceholder: 'Empresa Ltda.',
  refRelationship: 'Relação', refRelationshipPlaceholder: 'Gestor direto',

  templateTitle: 'Escolher Modelo',
  templateDesc: 'Selecione o layout e tema de cor que melhor se adequam ao seu perfil.',
  colorTheme: 'Tema de Cor', selectedLabel: 'Selecionado:',

  importTitle: 'Importar Currículo Existente',
  importDesc: 'Cole seu currículo em texto simples. Extrairemos suas informações automaticamente.',
  importWarning: 'A análise é heurística — revise os dados extraídos antes de exportar. Fotos não são importadas.',
  importPlaceholder: 'Cole seu currículo aqui…',
  parseCV: 'Analisar Currículo', applyToBuilder: 'Aplicar ao Editor', editText: '← Editar texto',
  importSuccess: 'Importado com sucesso!',
  importSuccessDesc: 'Revise e complete os campos ausentes no editor.',
  previewLabels: {
    name: 'Nome', email: 'E-mail', phone: 'Telefone', linkedin: 'LinkedIn',
    summary: 'Resumo', workExperience: 'Experiência Profissional', entries: 'entradas extraídas',
    education: 'Formação', skills: 'Habilidades', languages: 'Idiomas', certifications: 'Certificações',
    workPreview: 'Prévia da Experiência', noTitle: '(sem cargo)', notFound: 'não encontrado', moreSuffix: 'mais…',
  },

  characters: 'caracteres',
  noItemsYet: 'Nenhum item adicionado ainda.',
};

export const jaUI: MarketUI = {
  back: '戻る', next: '次へ', save: '保存', saving: '保存中…', saved: '保存済み',
  clear: 'クリア', clearConfirmTitle: 'すべてのデータをクリアしますか？',
  clearConfirmBody: 'この履歴書のすべての内容が削除されます。この操作は元に戻せません。',
  import: 'インポート', exportPDF: 'PDF 出力', generating: '生成中…',
  done: '完了！', failed: '失敗', cancel: 'キャンセル', add: '追加', apply: '適用',
  markets: '← マーケット', privacyOn: 'プライベート', privacyOff: 'プライバシー',

  personalInfoTitle: '個人情報',
  personalInfoDesc: '連絡先と基本情報を入力してください。',
  firstName: '名', firstNamePlaceholder: '太郎',
  lastName: '姓', lastNamePlaceholder: '田中',
  email: 'メールアドレス', emailPlaceholder: 'taro@example.com',
  phone: '電話番号', phonePlaceholder: '+81-90-0000-0000',
  city: '市区町村', cityPlaceholder: '渋谷区',
  country: '国', countryPlaceholder: '日本',
  linkedIn: 'LinkedIn URL', website: 'ウェブサイト / ポートフォリオ',

  maritalSelect: '選択してください', maritalSingle: '未婚',
  maritalMarried: '既婚', maritalDivorced: '離婚',
  maritalWidowed: '死別', maritalPreferNot: '回答しない',

  genderSelect: '選択してください', genderMale: '男性', genderFemale: '女性',
  genderOther: 'その他', genderPreferNot: '回答しない',

  objectiveDesc: '志望動機や自己PRの概要を記入してください。',
  objectivePlaceholder: '○○年より○○社にて○○業務に従事。チームリーダーとしてプロジェクト管理を担当し、業務効率化に貢献してきました。貴社の発展に貢献したいと考えております。',
  objectiveAimHint: '',
  skillsDesc: '資格・スキルを入力してください。',
  languagesDesc: '語学スキルと資格を入力してください。',
  certsDesc: '取得した免許・資格を記入してください。',
  refsDesc: '推薦者の情報を入力してください。',

  workJobTitle: '役職', workJobTitlePlaceholder: 'エンジニア',
  workCompany: '会社名', workCompanyPlaceholder: '株式会社〇〇',
  workLocation: '勤務地', workLocationPlaceholder: '東京都渋谷区',
  workEmploymentType: '雇用形態',
  workDescription: '業務内容', workDescPlaceholder: '・システム開発を担当し…',
  addWork: '職歴を追加', newPosition: '新しい職歴', newCompany: '会社名',
  employmentTypes: { fullTime: '正社員', partTime: 'パート・アルバイト', contract: '契約社員', freelance: 'フリーランス', internship: 'インターン' },

  addEducation: '学歴を追加', newDegree: '新しい学歴', newInstitution: '学校名',
  degree: '卒業区分', degreePlaceholder: '卒業・修了・中退',
  fieldOfStudy: '学科・専攻', fieldOfStudyPlaceholder: '情報工学科',
  institution: '学校名', institutionPlaceholder: '○○大学',
  location: '所在地', locationPlaceholder: '東京都',
  gpa: '成績（任意）', honors: '表彰・受賞',

  addSkill: '追加', skillPlaceholder: '例：Python、プロジェクト管理',
  skillCategory: 'カテゴリー（任意）', skillCategoryPlaceholder: '一般',
  noSkillsYet: 'スキルはまだ追加されていません。上記に入力してEnterを押してください。',
  skillLevels: ['初心者', '基礎', '中級', '上級', 'エキスパート'],

  addLanguage: '追加', languagePlaceholder: '例：英語、中国語',
  noLanguagesYet: '言語はまだ追加されていません。',
  nativeLabel: 'ネイティブ', langCertLabel: '資格・スコア', langCertPlaceholder: '例：TOEIC 800',

  addCertification: '免許・資格を追加', newCertification: '新しい資格',
  certName: '資格・免許名', certNamePlaceholder: '普通自動車免許',
  certIssuer: '発行機関', certIssuerPlaceholder: '〇〇協会',
  certDate: '取得年月', certExpiry: '有効期限',
  certCredential: '認証 ID / URL', certCredentialPlaceholder: 'ABC123 または https://…',

  addReference: '参照を追加', newReference: '新しい参照', newReferenceSubtitle: '職位・企業',
  refName: '氏名', refNamePlaceholder: '田中 花子',
  refJobTitle: '役職', refJobTitlePlaceholder: 'シニアマネージャー',
  refCompany: '会社名', refCompanyPlaceholder: '株式会社〇〇',
  refRelationship: '関係', refRelationshipPlaceholder: '直属の上司',

  templateTitle: 'テンプレートを選択',
  templateDesc: 'ご希望の職種に合ったレイアウトと配色テーマを選択してください。',
  colorTheme: '配色テーマ', selectedLabel: '選択済み：',

  importTitle: '既存の履歴書からインポート',
  importDesc: '既存の履歴書をテキストとして貼り付けてください。情報を自動的に抽出してフォームに入力します。',
  importWarning: '解析は自動です。エクスポート前に抽出されたデータを確認・修正してください。写真はインポートされません。',
  importPlaceholder: 'ここに履歴書のテキストを貼り付けてください…',
  parseCV: '履歴書を解析', applyToBuilder: 'ビルダーに適用', editText: '← テキストを編集',
  importSuccess: 'インポートが完了しました！',
  importSuccessDesc: 'ビルダーで不足しているフィールドを確認・入力してください。',
  previewLabels: {
    name: '氏名', email: 'メール', phone: '電話', linkedin: 'LinkedIn',
    summary: '概要', workExperience: '職歴', entries: '件抽出されました',
    education: '学歴', skills: 'スキル', languages: '言語', certifications: '資格',
    workPreview: '職歴プレビュー', noTitle: '（職位なし）', notFound: '見つかりません', moreSuffix: '件以上…',
  },

  characters: '文字',
  noItemsYet: 'まだ追加されていません。',
};
