import { MarketUI } from '@/types/market.types';

export const enUI: MarketUI = {
  back: 'Back', next: 'Next', save: 'Save', saving: 'Saving…', saved: 'Saved',
  clear: 'Clear', clearConfirmTitle: 'Clear all data?',
  clearConfirmBody: 'This will erase everything on this CV. This action cannot be undone.',
  import: 'Import', exportPDF: 'Export PDF', generating: 'Generating…',
  done: 'Done!', failed: 'Failed', cancel: 'Cancel', add: 'Add', apply: 'Apply',
  markets: '← Markets', privacyOn: 'Private', privacyOff: 'Privacy',

  personalInfoTitle: 'Personal Information',
  personalInfoDesc: 'Your contact details and basic information.',
  firstName: 'First Name', firstNamePlaceholder: 'John',
  lastName: 'Last Name', lastNamePlaceholder: 'Smith',
  email: 'Email', emailPlaceholder: 'john@example.com',
  phone: 'Phone', phonePlaceholder: '+1 555 000 0000',
  city: 'City', cityPlaceholder: 'New York',
  country: 'Country', countryPlaceholder: 'United States',
  linkedIn: 'LinkedIn URL', website: 'Website / Portfolio',

  maritalSelect: 'Select…', maritalSingle: 'Single',
  maritalMarried: 'Married', maritalDivorced: 'Divorced',
  maritalWidowed: 'Widowed', maritalPreferNot: 'Prefer not to say',

  workJobTitle: 'Job Title', workJobTitlePlaceholder: 'Software Engineer',
  workCompany: 'Company', workCompanyPlaceholder: 'Acme Corp',
  workLocation: 'Location', workLocationPlaceholder: 'New York, NY',
  workEmploymentType: 'Employment Type',
  workDescription: 'Description', workDescPlaceholder: '• Led development of…',
  addWork: 'Add Work Experience', newPosition: 'New Position', newCompany: 'Company name',
  employmentTypes: { fullTime: 'Full-time', partTime: 'Part-time', contract: 'Contract', freelance: 'Freelance', internship: 'Internship' },

  addEducation: 'Add Education', newDegree: 'New Degree', newInstitution: 'Institution',
  degree: 'Degree', degreePlaceholder: 'Bachelor of Science',
  fieldOfStudy: 'Field of Study', fieldOfStudyPlaceholder: 'Computer Science',
  institution: 'Institution', institutionPlaceholder: 'University of California',
  location: 'Location', locationPlaceholder: 'Berkeley, CA',
  gpa: 'GPA (optional)', honors: 'Honors / Awards',

  addSkill: 'Add', skillPlaceholder: 'e.g. Python, Project Management',
  skillCategory: 'Category (optional)', skillCategoryPlaceholder: 'General',
  noSkillsYet: 'No skills added yet. Type a skill above and press Enter.',
  skillLevels: ['Beginner', 'Basic', 'Intermediate', 'Advanced', 'Expert'],

  addLanguage: 'Add', languagePlaceholder: 'e.g. Spanish, French',
  noLanguagesYet: 'No languages added yet.',
  nativeLabel: 'Native', langCertLabel: 'Certification / Score', langCertPlaceholder: 'e.g. IELTS 7.5',

  addCertification: 'Add Certification', newCertification: 'New Certification',
  certName: 'Certification Name', certNamePlaceholder: 'AWS Solutions Architect',
  certIssuer: 'Issuing Organization', certIssuerPlaceholder: 'Amazon Web Services',
  certDate: 'Date Issued', certExpiry: 'Expiry Date',
  certCredential: 'Credential ID / URL', certCredentialPlaceholder: 'ABC123 or https://…',

  addReference: 'Add Reference', newReference: 'New Reference', newReferenceSubtitle: 'Title, Company',
  refName: 'Full Name', refNamePlaceholder: 'Jane Doe',
  refJobTitle: 'Job Title', refJobTitlePlaceholder: 'Senior Manager',
  refCompany: 'Company', refCompanyPlaceholder: 'Acme Corp',
  refRelationship: 'Relationship', refRelationshipPlaceholder: 'Direct manager',

  templateTitle: 'Choose a Template',
  templateDesc: 'Select the layout and color theme that best fits your target role.',
  colorTheme: 'Color Theme', selectedLabel: 'Selected:',

  importTitle: 'Import from Existing CV',
  importDesc: 'Paste your existing CV as plain text. We\'ll extract your information and fill in the form automatically.',
  importWarning: 'Parsing is heuristic — review and correct the extracted data before exporting. Photos are not imported.',
  importPlaceholder: 'Paste your CV text here…',
  parseCV: 'Parse CV', applyToBuilder: 'Apply to Builder', editText: '← Edit text',
  importSuccess: 'Imported successfully!',
  importSuccessDesc: 'Review and complete the missing fields in the builder.',
  previewLabels: {
    name: 'Name', email: 'Email', phone: 'Phone', linkedin: 'LinkedIn',
    summary: 'Summary', workExperience: 'Work Experience', entries: 'entries extracted',
    education: 'Education', skills: 'Skills', languages: 'Languages', certifications: 'Certifications',
    workPreview: 'Work Experience Preview', noTitle: '(no title)', notFound: 'not found', moreSuffix: 'more…',
  },

  characters: 'characters',
  noItemsYet: 'No items added yet.',
};

export const esUI: MarketUI = {
  back: 'Atrás', next: 'Siguiente', save: 'Guardar', saving: 'Guardando…', saved: 'Guardado',
  clear: 'Limpiar', clearConfirmTitle: '¿Limpiar todos los datos?',
  clearConfirmBody: 'Esto borrará todo en este CV. Esta acción no se puede deshacer.',
  import: 'Importar', exportPDF: 'Exportar PDF', generating: 'Generando…',
  done: '¡Listo!', failed: 'Error', cancel: 'Cancelar', add: 'Añadir', apply: 'Aplicar',
  markets: '← Mercados', privacyOn: 'Privado', privacyOff: 'Privacidad',

  personalInfoTitle: 'Información Personal',
  personalInfoDesc: 'Tus datos de contacto e información básica.',
  firstName: 'Nombre', firstNamePlaceholder: 'Juan',
  lastName: 'Apellido', lastNamePlaceholder: 'García',
  email: 'Correo Electrónico', emailPlaceholder: 'juan@ejemplo.com',
  phone: 'Teléfono', phonePlaceholder: '+54 555 000 0000',
  city: 'Ciudad', cityPlaceholder: 'Buenos Aires',
  country: 'País', countryPlaceholder: 'Argentina',
  linkedIn: 'URL de LinkedIn', website: 'Sitio Web / Portafolio',

  maritalSelect: 'Seleccionar', maritalSingle: 'Soltero/a',
  maritalMarried: 'Casado/a', maritalDivorced: 'Divorciado/a',
  maritalWidowed: 'Viudo/a', maritalPreferNot: 'Prefiero no decir',

  workJobTitle: 'Cargo', workJobTitlePlaceholder: 'Ingeniero de Software',
  workCompany: 'Empresa', workCompanyPlaceholder: 'Empresa S.A.',
  workLocation: 'Ubicación', workLocationPlaceholder: 'Buenos Aires, Argentina',
  workEmploymentType: 'Tipo de Empleo',
  workDescription: 'Descripción', workDescPlaceholder: '• Lideré el desarrollo de…',
  addWork: 'Añadir Experiencia Laboral', newPosition: 'Nuevo Puesto', newCompany: 'Nombre de la empresa',
  employmentTypes: { fullTime: 'Tiempo Completo', partTime: 'Tiempo Parcial', contract: 'Contrato', freelance: 'Freelance', internship: 'Pasantía' },

  addEducation: 'Añadir Educación', newDegree: 'Nuevo Título', newInstitution: 'Institución',
  degree: 'Título', degreePlaceholder: 'Licenciatura en Ciencias',
  fieldOfStudy: 'Área de Estudio', fieldOfStudyPlaceholder: 'Informática',
  institution: 'Institución', institutionPlaceholder: 'Universidad de Buenos Aires',
  location: 'Ubicación', locationPlaceholder: 'Buenos Aires, Argentina',
  gpa: 'Promedio (opcional)', honors: 'Honores / Premios',

  addSkill: 'Añadir', skillPlaceholder: 'p. ej. Python, Gestión de Proyectos',
  skillCategory: 'Categoría (opcional)', skillCategoryPlaceholder: 'General',
  noSkillsYet: 'Aún no hay habilidades. Escribe una arriba y presiona Enter.',
  skillLevels: ['Principiante', 'Básico', 'Intermedio', 'Avanzado', 'Experto'],

  addLanguage: 'Añadir', languagePlaceholder: 'p. ej. Inglés, Francés',
  noLanguagesYet: 'Aún no hay idiomas añadidos.',
  nativeLabel: 'Nativo/a', langCertLabel: 'Certificación / Puntaje', langCertPlaceholder: 'p. ej. IELTS 7.5',

  addCertification: 'Añadir Certificación', newCertification: 'Nueva Certificación',
  certName: 'Nombre de la Certificación', certNamePlaceholder: 'AWS Solutions Architect',
  certIssuer: 'Organización Emisora', certIssuerPlaceholder: 'Amazon Web Services',
  certDate: 'Fecha de Emisión', certExpiry: 'Fecha de Vencimiento',
  certCredential: 'ID de Credencial / URL', certCredentialPlaceholder: 'ABC123 o https://…',

  addReference: 'Añadir Referencia', newReference: 'Nueva Referencia', newReferenceSubtitle: 'Cargo, Empresa',
  refName: 'Nombre Completo', refNamePlaceholder: 'María García',
  refJobTitle: 'Cargo', refJobTitlePlaceholder: 'Gerente Senior',
  refCompany: 'Empresa', refCompanyPlaceholder: 'Empresa S.A.',
  refRelationship: 'Relación', refRelationshipPlaceholder: 'Jefe directo',

  templateTitle: 'Elegir Plantilla',
  templateDesc: 'Selecciona el diseño y tema de color que mejor se adapte a tu perfil.',
  colorTheme: 'Tema de Color', selectedLabel: 'Seleccionado:',

  importTitle: 'Importar CV Existente',
  importDesc: 'Pega tu CV como texto sin formato. Extraeremos tu información y rellenaremos el formulario automáticamente.',
  importWarning: 'El análisis es heurístico — revisa y corrige los datos extraídos antes de exportar. Las fotos no se importan.',
  importPlaceholder: 'Pega tu CV aquí…',
  parseCV: 'Analizar CV', applyToBuilder: 'Aplicar al Constructor', editText: '← Editar texto',
  importSuccess: '¡Importado con éxito!',
  importSuccessDesc: 'Revisa y completa los campos faltantes en el constructor.',
  previewLabels: {
    name: 'Nombre', email: 'Correo', phone: 'Teléfono', linkedin: 'LinkedIn',
    summary: 'Resumen', workExperience: 'Experiencia Laboral', entries: 'entradas extraídas',
    education: 'Educación', skills: 'Habilidades', languages: 'Idiomas', certifications: 'Certificaciones',
    workPreview: 'Vista Previa de Experiencia', noTitle: '(sin título)', notFound: 'no encontrado', moreSuffix: 'más…',
  },

  characters: 'caracteres',
  noItemsYet: 'Aún no hay elementos añadidos.',
};

export const jaUI: MarketUI = {
  back: '戻る', next: '次へ', save: '保存', saving: '保存中…', saved: '保存済み',
  clear: 'クリア', clearConfirmTitle: 'すべてのデータをクリアしますか？',
  clearConfirmBody: 'この履歴書のすべての内容が削除されます。この操作は元に戻せません。',
  import: 'インポート', exportPDF: 'PDF 出力', generating: '生成中…',
  done: '完了！', failed: '失敗', cancel: 'キャンセル', add: '追加', apply: '適用',
  markets: '← マーケット', privacyOn: 'プライベート', privacyOff: 'プライバシー',

  personalInfoTitle: '個人情報',
  personalInfoDesc: '連絡先と基本情報を入力してください。',
  firstName: '名', firstNamePlaceholder: '太郎',
  lastName: '姓', lastNamePlaceholder: '田中',
  email: 'メールアドレス', emailPlaceholder: 'taro@example.com',
  phone: '電話番号', phonePlaceholder: '+81-90-0000-0000',
  city: '市区町村', cityPlaceholder: '渋谷区',
  country: '国', countryPlaceholder: '日本',
  linkedIn: 'LinkedIn URL', website: 'ウェブサイト / ポートフォリオ',

  maritalSelect: '選択してください', maritalSingle: '未婚',
  maritalMarried: '既婚', maritalDivorced: '離婚',
  maritalWidowed: '死別', maritalPreferNot: '回答しない',

  workJobTitle: '役職', workJobTitlePlaceholder: 'エンジニア',
  workCompany: '会社名', workCompanyPlaceholder: '株式会社〇〇',
  workLocation: '勤務地', workLocationPlaceholder: '東京都渋谷区',
  workEmploymentType: '雇用形態',
  workDescription: '業務内容', workDescPlaceholder: '・システム開発を担当し…',
  addWork: '職歴を追加', newPosition: '新しい職歴', newCompany: '会社名',
  employmentTypes: { fullTime: '正社員', partTime: 'パート・アルバイト', contract: '契約社員', freelance: 'フリーランス', internship: 'インターン' },

  addEducation: '学歴を追加', newDegree: '新しい学歴', newInstitution: '学校名',
  degree: '卒業区分', degreePlaceholder: '卒業・修了・中退',
  fieldOfStudy: '学科・専攻', fieldOfStudyPlaceholder: '情報工学科',
  institution: '学校名', institutionPlaceholder: '○○大学',
  location: '所在地', locationPlaceholder: '東京都',
  gpa: '成績（任意）', honors: '表彰・受賞',

  addSkill: '追加', skillPlaceholder: '例：Python、プロジェクト管理',
  skillCategory: 'カテゴリー（任意）', skillCategoryPlaceholder: '一般',
  noSkillsYet: 'スキルはまだ追加されていません。上記に入力してEnterを押してください。',
  skillLevels: ['初心者', '基礎', '中級', '上級', 'エキスパート'],

  addLanguage: '追加', languagePlaceholder: '例：英語、中国語',
  noLanguagesYet: '言語はまだ追加されていません。',
  nativeLabel: 'ネイティブ', langCertLabel: '資格・スコア', langCertPlaceholder: '例：TOEIC 800',

  addCertification: '免許・資格を追加', newCertification: '新しい資格',
  certName: '資格・免許名', certNamePlaceholder: '普通自動車免許',
  certIssuer: '発行機関', certIssuerPlaceholder: '〇〇協会',
  certDate: '取得年月', certExpiry: '有効期限',
  certCredential: '認証 ID / URL', certCredentialPlaceholder: 'ABC123 または https://…',

  addReference: '参照を追加', newReference: '新しい参照', newReferenceSubtitle: '職位・企業',
  refName: '氏名', refNamePlaceholder: '田中 花子',
  refJobTitle: '役職', refJobTitlePlaceholder: 'シニアマネージャー',
  refCompany: '会社名', refCompanyPlaceholder: '株式会社〇〇',
  refRelationship: '関係', refRelationshipPlaceholder: '直属の上司',

  templateTitle: 'テンプレートを選択',
  templateDesc: 'ご希望の職種に合ったレイアウトと配色テーマを選択してください。',
  colorTheme: '配色テーマ', selectedLabel: '選択済み：',

  importTitle: '既存の履歴書からインポート',
  importDesc: '既存の履歴書をテキストとして貼り付けてください。情報を自動的に抽出してフォームに入力します。',
  importWarning: '解析は自動です。エクスポート前に抽出されたデータを確認・修正してください。写真はインポートされません。',
  importPlaceholder: 'ここに履歴書のテキストを貼り付けてください…',
  parseCV: '履歴書を解析', applyToBuilder: 'ビルダーに適用', editText: '← テキストを編集',
  importSuccess: 'インポートが完了しました！',
  importSuccessDesc: 'ビルダーで不足しているフィールドを確認・入力してください。',
  previewLabels: {
    name: '氏名', email: 'メール', phone: '電話', linkedin: 'LinkedIn',
    summary: '概要', workExperience: '職歴', entries: '件抽出されました',
    education: '学歴', skills: 'スキル', languages: '言語', certifications: '資格',
    workPreview: '職歴プレビュー', noTitle: '（職位なし）', notFound: '見つかりません', moreSuffix: '件以上…',
  },

  characters: '文字',
  noItemsYet: 'まだ追加されていません。',
};
