import { MarketConfig } from '@/types/market.types';

export const usConfig: MarketConfig = {
  market: 'us',
  name: 'United States',
  locale: 'en-US',
  pageSize: 'Letter',
  direction: 'ltr',
  color: '#2563eb',
  accentColor: '#1d4ed8',
  themes: [
    { id: 'us-blue',   name: 'Navy',    primary: '#2563eb', accent: '#1d4ed8', light: '#dbeafe' },
    { id: 'us-slate',  name: 'Slate',   primary: '#475569', accent: '#334155', light: '#f1f5f9' },
    { id: 'us-teal',   name: 'Teal',    primary: '#0d9488', accent: '#0f766e', light: '#ccfbf1' },
    { id: 'us-violet', name: 'Violet',  primary: '#7c3aed', accent: '#6d28d9', light: '#ede9fe' },
    { id: 'us-rose',   name: 'Rose',    primary: '#e11d48', accent: '#be123c', light: '#ffe4e6' },
    { id: 'us-mono',   name: 'Monochrome', primary: '#111827', accent: '#374151', light: '#f3f4f6' },
  ],
  fields: {
    photo: { visibility: 'hidden' },
    dateOfBirth: { visibility: 'hidden' },
    nationality: { visibility: 'hidden' },
    maritalStatus: { visibility: 'hidden' },
    idNumber: { visibility: 'hidden' },
    furigana: { visibility: 'hidden' },
    gender: { visibility: 'hidden' },
    nearestStation: { visibility: 'hidden' },
    commuteTime: { visibility: 'hidden' },
    emergencyContact: { visibility: 'hidden' },
    personalSeal: { visibility: 'hidden' },
  },
  sections: {
    objective: { enabled: true, required: false, order: 0, label: 'Professional Summary' },
    workExperience: { enabled: true, required: true, order: 1, label: 'Work Experience' },
    education: { enabled: true, required: true, order: 2, label: 'Education' },
    skills: { enabled: true, required: false, order: 3, label: 'Skills' },
    languages: { enabled: true, required: false, order: 4, label: 'Languages' },
    certifications: { enabled: true, required: false, order: 5, label: 'Certifications & Licenses' },
    references: { enabled: false, required: false, order: 6, label: 'References' },
    selfPromotion: { enabled: false, required: false, order: 7 },
    reasonForApplication: { enabled: false, required: false, order: 8 },
  },
  pageLimitSuggestion: 1,
  languageLevelSystem: 'generic',
  dateFormat: 'MMM yyyy',
  enableATSSuggestions: true,
  templates: [
    { id: 'us-classic', name: 'Classic', description: 'Traditional ATS-friendly single-column format' },
    { id: 'us-modern',  name: 'Modern',  description: 'Clean two-column layout with accent sidebar' },
  ],
};
